version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskforge-postgres
    environment:
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: Abc123!@#
      POSTGRES_DB: taskforge_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
